// Machine-readable backlog for repo seeding (source of truth: docs/BACKLOG.md)
export const OWNER = 'aaronkisac';
export const REPO = 'aaronkisac/dentaliva';

export const MILESTONES = [
  { n: 1, name: '1 — Foundations', desc: 'Monorepo scaffold, shared config packages, CI, repo governance' },
  { n: 2, name: '2 — Design tokens & design system', desc: 'Token pipeline + tested, accessible UI primitives (reusable components first)' },
  { n: 3, name: '3 — Sanity schema & Studio', desc: 'Shared schema kernel, clinic documents, TypeGen + typed queries, Studio' },
  { n: 4, name: '4 — Page templates & composition', desc: 'Site-config engine and all page templates over Sanity content' },
  { n: 5, name: '5 — Content migration', desc: 'Crawl dentaliva.com → transform → Sanity import, NAP reconciliation' },
  { n: 6, name: '6 — SEO hooks', desc: 'Metadata/JSON-LD builders, per-domain sitemap/robots, hreflang, redirects' },
  { n: 7, name: '7 — Callback form & Worker', desc: 'Turnstile + Zod + Resend pipeline, zero persistence, mocked E2E' },
  { n: 8, name: '8 — Performance & accessibility hardening', desc: 'LCP/CLS, keyboard/axe audit, Lighthouse + bundle budgets' },
  { n: 9, name: '9 — Deployment & rebuild pipeline', desc: 'Workers prod/staging, CSP headers, webhook → deploy hook, previews' },
  { n: 10, name: '10 — Starter extraction & new-site docs', desc: 'Template repo, under-1-hour runbook, ZCode skills, handover' },
];

export const LABELS = [
  ['epic/1-foundations', '1d76db'], ['epic/2-design-system', '006b75'], ['epic/3-sanity', '5319e7'],
  ['epic/4-page-templates', 'b60205'], ['epic/5-migration', 'd93f0b'], ['epic/6-seo', '0e8a16'],
  ['epic/7-form', 'c2e0c6'], ['epic/8-perf-a11y', 'fef2c0'], ['epic/9-deployment', '0052cc'],
  ['epic/10-starter', '7057ff'],
  ['type/feature', 'a2eeef'], ['type/platform', 'e99695'], ['type/docs', '0075ca'],
  ['type/ci', 'f9d0c4'], ['type/test', 'fbca04'], ['type/migration', 'bfdadc'],
  ['size/S', '0e8a16'], ['size/M', 'e99695'],
];

const t = (type) => `type/${type}`;
// id, epic, type, size, deps, title, statement, ac[], tests
export const ISSUES = [
  // ── Epic 1 — Foundations
  { id: 'FND-1', e: 1, ty: 'platform', s: 'S', d: '—', title: 'Scaffold Turborepo workspace',
    st: 'As a developer, I need the pnpm + Turborepo workspace scaffolded so all later work lands in a structured monorepo.',
    ac: ['`apps/web`, `apps/studio` and `packages/{tokens,ui,clinic,sanity-schema,seo,lib,config}` exist per ARCHITECTURE §3', '`pnpm i && pnpm build` is green', 'turbo.json uses `tasks` and lint/typecheck/test/build run across the workspace'],
    ts: 'CI pipeline runs all tasks on the scaffold' },
  { id: 'FND-2', e: 1, ty: 'platform', s: 'M', d: 'FND-1', title: 'Shared config packages (tsconfig/eslint/prettier/tailwind/vitest)',
    st: 'As a developer, I need shared tooling configs so every package has identical strict standards.',
    ac: ['tsconfig bases: strict + `noUncheckedIndexedAccess`', 'ESLint flat config: TS strict, jsx-a11y, package import boundaries', 'Prettier, Tailwind v4 preset, Vitest preset with coverage thresholds (100% ui/lib/seo/clinic-schema, ≥90% global)'],
    ts: 'Boundary rule demonstrably fails on a bad import (fixture test)' },
  { id: 'FND-3', e: 1, ty: 'platform', s: 'S', d: 'FND-1', title: 'GitHub repo governance (protection, template, labels, board)',
    st: 'As a maintainer, I need branch protection and project hygiene so main stays releasable.',
    ac: ['Branch protection on main requires all checks', 'PR template applies to new PRs', 'Milestones + labels exist'],
    ts: 'Verified once that an unechecked PR cannot merge' },
  { id: 'FND-4', e: 1, ty: 'ci', s: 'M', d: 'FND-2', title: 'CI pipeline: lint → typecheck → unit+coverage → build',
    st: 'As a developer, I need CI to enforce quality on every PR.',
    ac: ['GitHub Actions runs lint, typecheck, unit+coverage thresholds, build of web+studio', 'pnpm store cache configured'],
    ts: 'Pipeline green on sample PR; failing check blocks merge (verified once)' },
  { id: 'FND-5', e: 1, ty: 'ci', s: 'S', d: 'FND-1', title: 'Conventional Commits (commitlint + Husky + lint-staged)',
    st: 'As a maintainer, I want commit conventions enforced so history stays readable.',
    ac: ['commitlint (Conventional Commits) locally + in CI', 'lint-staged runs eslint/prettier on staged files'],
    ts: 'Bad commit message rejected locally and in CI' },
  { id: 'FND-6', e: 1, ty: 'ci', s: 'S', d: 'FND-4', title: 'Renovate + pnpm audit gate',
    st: 'As a maintainer, I need automated dependency updates and a vulnerability gate.',
    ac: ['Renovate config: weekly schedule, grouped minor/patch, individual majors', '`pnpm audit` gate in CI'],
    ts: 'Gate demonstrably fails on a vulnerable fixture' },

  // ── Epic 2 — Design tokens & design system
  { id: 'DSN-1', e: 2, ty: 'feature', s: 'M', d: 'FND-2', title: 'Token extraction: prototype → packages/tokens + Tailwind @theme',
    st: 'As a developer, I need the navy/gold prototype design system promoted to reviewed tokens so no design values live outside tokens.',
    ac: ['tokens.ts → CSS custom properties emission; Tailwind v4 `@theme` mapping in packages/config', 'Navy/gold contrast pairs validated AA in token tests', 'Visual smoke page renders token set'],
    ts: 'Token unit tests + AA contrast tests' },
  { id: 'DSN-2', e: 2, ty: 'feature', s: 'S', d: 'DSN-1', title: 'Typography: self-hosted Cormorant Garamond + Montserrat, type scale',
    st: 'As a user, I need brand typography self-hosted so fonts add no external request and no CLS.',
    ac: ['`next/font` loads both families at build (self-hosted)', 'Type scale tokens applied (fluid sizes)'],
    ts: 'Build output contains self-hosted font files; scale snapshot test' },
  { id: 'DSN-3', e: 2, ty: 'feature', s: 'M', d: 'DSN-1, DSN-2', title: 'UI primitives batch 1 (Button, Container/Section, Heading/Text, Link)',
    st: 'As a developer, I need base primitives so pages compose from tested parts.',
    ac: ['cva variants; polymorphic `as` on Button; forwardRef on interactive elements', 'focus-visible styles from tokens'],
    ts: 'Render/variant/interaction tests + jest-axe per component' },
  { id: 'DSN-4', e: 2, ty: 'feature', s: 'M', d: 'DSN-3', title: 'UI primitives batch 2 (Card, Badge/Tag, Accordion)',
    st: 'As a developer, I need content primitives including a keyboard-complete FAQ accordion.',
    ac: ['Accordion: aria-expanded/controls, keyboard operable', 'Card/Badge variants from tokens'],
    ts: 'Interaction tests + jest-axe' },
  { id: 'DSN-5', e: 2, ty: 'feature', s: 'M', d: 'DSN-3', title: 'Header + Footer (responsive nav, mobile menu with focus trap)',
    st: 'As a user, I need site-wide navigation usable on all breakpoints.',
    ac: ['Responsive nav with mobile menu; focus trap + Esc close; skip link present', 'Footer driven by siteSettings data'],
    ts: 'Mobile menu E2E; axe; screenshots at 360/768/1024/1440' },
  { id: 'DSN-6', e: 2, ty: 'feature', s: 'S', d: 'DSN-3', title: 'Motion primitives: Reveal with prefers-reduced-motion',
    st: 'As a user with reduced-motion, I need animations suppressed.',
    ac: ['Reveal (IntersectionObserver, stagger) gated by prefers-reduced-motion', 'Ambient animations pause under reduced motion'],
    ts: 'Reduced-motion test proves animations skipped' },
  { id: 'DSN-7', e: 2, ty: 'feature', s: 'M', d: 'DSN-3', title: 'Form primitives (Input, Textarea, Select, Checkbox, FieldError)',
    st: 'As a developer, I need accessible form primitives so the callback form composes from tested parts.',
    ac: ['aria-describedby/aria-invalid wiring', 'error display via FieldError'],
    ts: 'Wiring tests + jest-axe' },

  // ── Epic 3 — Sanity schema & Studio
  { id: 'SAN-1', e: 3, ty: 'feature', s: 'M', d: 'FND-2', title: 'Schema kernel: localized fields, seo, imageWithAlt, blocks',
    st: 'As an editor, I need the shared schema kernel so every document type is consistent and validated.',
    ac: ['`defineLocalizedField` ({tr,en}, tr required)', '`seo` object (metaTitle, metaDescription, ogImage, noIndex, canonicalOverride)', '`imageWithAlt` with mandatory localized alt + hotspot; `blockSection`, `cta`, `stat`, `openingHours`'],
    ts: 'Schema validation tests (missing alt / empty tr rejected); TypeGen extracts' },
  { id: 'SAN-2', e: 3, ty: 'feature', s: 'M', d: 'SAN-1', title: 'Clinic core documents: treatment, doctor, branch',
    st: 'As an editor, I need clinic core documents so the site content is manageable.',
    ac: ['Fields per ARCHITECTURE §5; unique slug validation; cross-refs treatment↔doctor'],
    ts: 'Validation tests; preview structures compile' },
  { id: 'SAN-3', e: 3, ty: 'feature', s: 'M', d: 'SAN-1', title: 'Clinic supporting documents: faq, testimonial, legalPage, siteSettings, homePage, redirect, blogPost',
    st: 'As an editor, I need supporting documents so all page content and 301s are CMS-managed.',
    ac: ['All seven document types with validation', '`redirect` from→to uniqueness'],
    ts: 'Validation tests' },
  { id: 'SAN-4', e: 3, ty: 'platform', s: 'M', d: 'SAN-2, SAN-3', title: 'Studio app: structure, desks, previews, per-domain deploy config',
    st: 'As an editor, I need a usable Studio so content work is efficient.',
    ac: ['Structure/desks per document type with sensible defaults', 'Env-driven project/dataset (deployed per domain)'],
    ts: 'Studio builds; env switch picks correct project/dataset (fixture)' },
  { id: 'SAN-5', e: 3, ty: 'feature', s: 'M', d: 'SAN-2, SAN-3', title: 'TypeGen wiring + typed GROQ query library',
    st: 'As a developer, I need typed queries so content fetches are type-safe end to end.',
    ac: ['`sanity schema extract` → `sanity typegen generate` as prebuild', 'Queries via defineQuery() in packages/sanity-schema/queries.ts'],
    ts: 'Queries typecheck against generated types; unit tests vs fixture dataset' },
  { id: 'SAN-6', e: 3, ty: 'platform', s: 'S', d: 'SAN-4', title: 'Platform: create dentaliva-com Sanity project + datasets + CORS + Studio deploy',
    st: 'As the team, we need the real Sanity project so content work starts.',
    ac: ['`dentaliva-com` project with production + staging datasets', 'CORS for local + production domains', 'Studio deployed'],
    ts: 'Anonymous read works on production dataset' },

  // ── Epic 4 — Page templates & composition
  { id: 'PGT-1', e: 4, ty: 'feature', s: 'M', d: 'FND-2', title: 'Site config system (sites/<id>.config.ts + SITE_ID env wiring)',
    st: 'As a developer, I need a typed per-domain config so adding a domain is configuration only (ADR-004).',
    ac: ['Config schema: domain, locales, sanity ids, feature flags, section presets, sisterDomains', 'Unknown SITE_ID fails the build with a clear error'],
    ts: 'Config validation tests' },
  { id: 'PGT-2', e: 4, ty: 'feature', s: 'M', d: 'SAN-5, DSN-5', title: 'App shell: layout, header/footer from siteSettings, 404',
    st: 'As a visitor, I need a consistent shell driven by CMS settings.',
    ac: ['Static-export-safe layout; NAP/socials from siteSettings', 'Custom 404'],
    ts: 'Build emits static HTML; axe green' },
  { id: 'PGT-3', e: 4, ty: 'feature', s: 'M', d: 'PGT-2', title: 'Section composition engine + home template',
    st: 'As an editor, I need section presets so each site can compose its home differently.',
    ac: ['Site config section presets render home sections in order', 'Section content from homePage document'],
    ts: 'Preset reordering reflected in build; home E2E journey' },
  { id: 'PGT-4', e: 4, ty: 'feature', s: 'M', d: 'PGT-3', title: 'Treatment templates: list + detail',
    st: 'As a visitor, I need treatment list/detail pages generated from Sanity.',
    ac: ['generateStaticParams from slugs; all seeded treatments prerender', 'Body portable text, FAQs, related doctors'],
    ts: 'Prerender count matches fixture; detail E2E' },
  { id: 'PGT-5', e: 4, ty: 'feature', s: 'S', d: 'PGT-3', title: 'Doctor templates: list + detail',
    st: 'As a visitor, I need doctor profiles.',
    ac: ['List + detail from doctor documents'],
    ts: 'Prerender count; axe' },
  { id: 'PGT-6', e: 4, ty: 'feature', s: 'S', d: 'PGT-3', title: 'Branch templates: list + detail',
    st: 'As a visitor, I need branch pages with address, hours and map link.',
    ac: ['List + detail from branch documents'],
    ts: 'Prerender count; axe' },
  { id: 'PGT-7', e: 4, ty: 'feature', s: 'M', d: 'PGT-2', title: 'Static pages: about, gallery (a11y lightbox), contact, legal',
    st: 'As a visitor, I need about/gallery/contact/legal pages.',
    ac: ['Gallery grid + keyboard-operable lightbox', 'Contact shows NAP + map link; legal pages from legalPage docs'],
    ts: 'axe; lightbox keyboard tests' },
  { id: 'PGT-8', e: 4, ty: 'feature', s: 'M', d: 'PGT-3', title: 'Blog templates: index (build-time pagination) + post detail',
    st: 'As a visitor, I need the blog.',
    ac: ['Index paginated at build; post detail renders portable text', 'Custom renderers for links/images/blockquotes'],
    ts: 'Renderer unit tests; prerender checks' },
  { id: 'PGT-9', e: 4, ty: 'feature', s: 'S', d: 'SAN-1', title: 'Localization rendering rules (empty-locale fallback policy)',
    st: 'As a maintainer, I need a documented policy for missing EN so half-translated pages never ship.',
    ac: ['Fallback rules implemented + documented', 'TR-only v1 ships no locale segment'],
    ts: 'Fallback unit tests' },
  { id: 'PGT-10', e: 4, ty: 'feature', s: 'S', d: 'SAN-5, PGT-1', title: 'Chatbot JSON API (prototype contract) as static route handlers',
    st: 'As the chatbot integrator, I need the prototype JSON contract preserved so tooling keeps working.',
    ac: ['force-static handlers emit /api/{clinic,services,doctors,faq,slots}.json from Sanity', 'Feature-flagged per site'],
    ts: 'Contract tests vs prototype api/*.json shapes' },

  // ── Epic 5 — Content migration
  { id: 'MIG-1', e: 5, ty: 'migration', s: 'M', d: '—', title: 'Crawler: sitemap-driven scrape of dentaliva.com → normalized JSON',
    st: 'As a developer, I need a one-off crawler so migration starts from accurate, fresh data.',
    ac: ['Sitemap-driven fetch, normalized JSON per content type', 'Polite rate limit, robots-respecting'],
    ts: 'Fixture-based transform tests' },
  { id: 'MIG-2', e: 5, ty: 'migration', s: 'M', d: 'MIG-1, SAN-3', title: 'Transform to Sanity NDJSON + NAP reconciliation',
    st: 'As the team, we need core content mapped to Sanity documents with NAP verified against the live site.',
    ac: ['Treatments/doctors/branches/faq/testimonials/legal/settings transformed', 'NAP diff report (live wins) reviewed; deviations logged'],
    ts: 'Round-trip validation of NDJSON' },
  { id: 'MIG-3', e: 5, ty: 'migration', s: 'M', d: 'MIG-2', title: 'Blog transform: ~30 curated posts + ~100 redirect docs',
    st: 'As the SEO manager, I need substantial posts migrated and stub URLs 301-planned.',
    ac: ['~30 substantial posts → blogPost; stubs → redirect docs'],
    ts: 'Redirect count matches stub list; portable text valid' },
  { id: 'MIG-4', e: 5, ty: 'migration', s: 'M', d: 'MIG-2', title: 'Asset pipeline: images → Sanity assets, alt seeding, LQIP',
    st: 'As a developer, I need all images in Sanity so nothing hotlinks the old CDN.',
    ac: ['Download → upload with alt text seeding and LQIP metadata'],
    ts: 'Import manifest verified; zero hotlinks remain' },
  { id: 'MIG-5', e: 5, ty: 'migration', s: 'M', d: 'MIG-4, PGT-4', title: 'Import + verify: sanity import, spot checks, client sign-off',
    st: 'As the team, we need imported content verified against the live site.',
    ac: ['Import succeeds; page-vs-live spot check checklist', 'EN placeholder policy reviewed with client'],
    ts: 'TR site renders entirely from Sanity only' },

  // ── Epic 6 — SEO hooks
  { id: 'SEO-1', e: 6, ty: 'feature', s: 'M', d: 'SAN-1', title: 'packages/seo metadata builder (title/desc/canonical/OG/Twitter)',
    st: 'As the SEO manager, I need every page to emit complete, CMS-driven meta tags.',
    ac: ['Builder from seo objects with sensible fallbacks', 'Length validation'],
    ts: 'Snapshot + fallback tests (100% coverage package)' },
  { id: 'SEO-2', e: 6, ty: 'feature', s: 'M', d: 'SEO-1, PGT-3', title: 'JSON-LD: Dentist/MedicalClinic, BreadcrumbList, FAQPage',
    st: 'As the SEO manager, I need structured data on relevant templates.',
    ac: ['Dentist/MedicalClinic from siteSettings; BreadcrumbList per template; FAQPage where FAQs render'],
    ts: 'schema.org shape validation tests' },
  { id: 'SEO-3', e: 6, ty: 'feature', s: 'S', d: 'PGT-1', title: 'Per-domain sitemap.xml + robots.txt with dormant hreflang',
    st: 'As the SEO manager, I need per-domain sitemaps with hreflang ready for sister domains.',
    ac: ['app/sitemap.ts + robots.ts per domain', 'hreflang alternates emitted from sisterDomains config once ≥2 translated domains'],
    ts: 'Sitemap XML snapshot tests' },
  { id: 'SEO-4', e: 6, ty: 'feature', s: 'S', d: 'SAN-3, PGT-1', title: '_redirects generation from redirect docs',
    st: 'As the SEO manager, I need dropped blog URLs to 301 rather than 404.',
    ac: ['Build generates _redirects from redirect documents'],
    ts: 'File matches docs; 301 verified via wrangler dev' },

  // ── Epic 7 — Callback form & Worker
  { id: 'FRM-1', e: 7, ty: 'feature', s: 'S', d: 'FND-2', title: 'Form schema: Zod (name, TR phone, time, KVKK consent) + TR error copy',
    st: 'As a developer, I need one validation schema shared by client and worker.',
    ac: ['Zod schema in packages/lib/forms; Turkish messages', 'TR phone validation'],
    ts: 'Schema unit tests (100% coverage package)' },
  { id: 'FRM-2', e: 7, ty: 'feature', s: 'M', d: 'FRM-1, DSN-7', title: 'Client form: RHF + Turnstile + honeypot + KVKK consent + inline states',
    st: 'As a visitor, I need an accessible, trustworthy callback form.',
    ac: ['RHF + invisible Turnstile + honeypot', 'Consent checkbox linking aydınlatma metni', 'Inline success/error, no alert()'],
    ts: 'Component tests (validation, states)' },
  { id: 'FRM-3', e: 7, ty: 'platform', s: 'M', d: 'FRM-1', title: 'Worker POST /api/callback: Zod → Turnstile → rate limit → Resend',
    st: 'As the clinic, I need submissions emailed reliably with spam protection and no data persistence.',
    ac: ['Pipeline per ADR-007; 400/429/502 mapping', 'Secrets only in Worker env; zero KV/D1/R2 writes'],
    ts: 'Worker tests with mocked Siteverify+Resend; CI grep proves secrets absent from client bundle' },
  { id: 'FRM-4', e: 7, ty: 'test', s: 'S', d: 'FRM-2, FRM-3', title: 'E2E form journey under wrangler dev + MOCK_EXTERNAL=1',
    st: 'As a developer, I need the full form path proven in CI.',
    ac: ['Success, validation failure, rate-limit, mail-failure scenarios green'],
    ts: '4 Playwright scenarios' },

  // ── Epic 8 — Perf & a11y
  { id: 'PRF-1', e: 8, ty: 'feature', s: 'M', d: 'PGT-3', title: 'LCP/CLS pass: hero priority, LQIP, font display, sizes audit',
    st: 'As a visitor on slow 4G, I need the page usable fast.',
    ac: ['LCP < 2.0s (Moto G Power / slow 4G profile)', 'CLS < 0.05'],
    ts: 'Lab measurements recorded; regressions caught by PRF-3' },
  { id: 'PRF-2', e: 8, ty: 'test', s: 'M', d: 'PGT-4', title: 'Accessibility audit: keyboard sweep, focus, landmarks, reduced motion',
    st: 'As a keyboard/screen-reader user, I need every template fully operable (WCAG 2.2 AA).',
    ac: ['axe clean on all templates', 'Manual keyboard checklist documented and passing'],
    ts: 'axe scans + documented manual pass' },
  { id: 'PRF-3', e: 8, ty: 'ci', s: 'M', d: 'DEP-1', title: 'Lighthouse CI wiring + budgets (with plain-lighthouse fallback)',
    st: 'As a maintainer, I need performance budgets enforced in CI.',
    ac: ['≥95 all four categories on preview deploys', 'lhci↔Lighthouse-13 compat verified; else plain lighthouse + assertion script'],
    ts: 'Budgets enforced (verified once by deliberate failure)' },
  { id: 'PRF-4', e: 8, ty: 'ci', s: 'S', d: 'FND-4', title: 'Bundle budget: ≤90KB first-load JS + "use client" audit',
    st: 'As a maintainer, I need client JS bounded.',
    ac: ['First-load JS ≤ 90KB gzip shared route enforced in CI', '"use client" surfaces audited'],
    ts: 'CI check from build stats fails on regression' },

  // ── Epic 9 — Deployment
  { id: 'DEP-1', e: 9, ty: 'platform', s: 'M', d: 'FND-1', title: 'Workers projects: production + staging (Access) + custom domain',
    st: 'As the team, we need dentaliva.com live on Workers with static assets.',
    ac: ['Production + staging projects; staging behind Cloudflare Access', 'Custom domain bound (DNS on CF nameservers — prerequisite confirmed)'],
    ts: 'Deploys serve the static build; domain resolves' },
  { id: 'DEP-2', e: 9, ty: 'feature', s: 'S', d: 'DEP-1', title: '_headers: CSP + security headers as reviewed code',
    st: 'As a maintainer, I need hardened response headers without Next headers().',
    ac: ['CSP (self; Sanity+imgix; Turnstile; youtube-nocookie; self fonts), HSTS, XCTO, Referrer-Policy, Permissions-Policy, COOP'],
    ts: 'Header assertions in E2E; CSP report-clean' },
  { id: 'DEP-3', e: 9, ty: 'platform', s: 'S', d: 'SAN-6, DEP-1', title: 'Sanity webhook → deploy hook + rebuild-latency runbook',
    st: 'As an editor, I need publishes to reach the live site automatically.',
    ac: ['GROQ webhook (published only) → Workers deploy hook', 'Runbook documents ~2–3 min budget'],
    ts: 'Live verification: publish triggers rebuild; latency measured' },
  { id: 'DEP-4', e: 9, ty: 'ci', s: 'M', d: 'DEP-1', title: 'PR previews + main→production deploys',
    st: 'As a reviewer, I need a preview URL per PR.',
    ac: ['Workers Git integration: PR → preview; main → production only'],
    ts: 'Preview verified on a sample PR' },
  { id: 'DEP-5', e: 9, ty: 'feature', s: 'S', d: 'DEP-1', title: 'Cloudflare Web Analytics (cookieless)',
    st: 'As the client, I need privacy-friendly analytics with no cookie banner.',
    ac: ['Beacon on all pages; no cookies introduced'],
    ts: 'E2E assertion: no cookies set' },

  // ── Epic 10 — Starter
  { id: 'STR-1', e: 10, ty: 'platform', s: 'M', d: 'PGT-1, MIG-5', title: 'Genericize repo as GitHub template repository',
    st: 'As a starter consumer, I need clinic specifics isolated so a new vertical swaps cleanly.',
    ac: ['Clinic content confined to packages/clinic + sites config', 'README + seed docs for new clients', 'Repo marked as template'],
    ts: 'Fresh clone + checklist produces a building site (dry run)' },
  { id: 'STR-2', e: 10, ty: 'docs', s: 'M', d: 'DEP-3', title: 'docs/runbooks/new-site.md — the "under 1 hour" checklist',
    st: 'As an operator, I need the new-site runbook validated by a real dry run.',
    ac: ['Checklist: config file → Sanity project/datasets → Workers → DNS → webhook → Turnstile/Resend → seed', 'Timings recorded against the 1-hour target'],
    ts: 'Dry run executed; runbook updated from findings' },
  { id: 'STR-3', e: 10, ty: 'docs', s: 'M', d: 'STR-2', title: 'ZCode project skills: component-authoring, pr-workflow, sanity-schema, new-client-site',
    st: 'As a ZCode agent, I need project skills so future sessions follow conventions.',
    ac: ['.zcode/skills/<name>/SKILL.md ×4 with valid frontmatter (name, description, when_to_use)'],
    ts: 'Skills load in ZCode' },
  { id: 'STR-4', e: 10, ty: 'docs', s: 'S', d: 'STR-1', title: 'Handover: canonical docs + account transfer checklist',
    st: 'As the client, I need ownership of all accounts and canonical docs at handover.',
    ac: ['AGENTS.md/architecture canonical in dentaliva', 'Transfer checklist: Sanity, Cloudflare, GitHub, Resend, domain DNS'],
    ts: 'Checklist reviewed with Aaron' },
];
